name: Demo
description: Use this form if you'd like to have a demo of this project in action. 
title: "[Question]: "
labels: ["question"]
assignees:
  - weeyin83
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: Demorequest
    attributes:
      label: Demorequest
      description: Let me know what kind of demo you'd like to see and why and I will reach out to discuss. 
      render: shell
